name = "HybridSmoothers"
uuid = "da817a5f-7d49-401a-84b6-75d77c2330d5"
version = "0.1.0"
authors = ["Abdelrahman F. Abdelrahman and Dennis Ogiermann <termi-official@users.noreply.github.com>"]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
